### ISSUE TITLE
WBGT does not include any humidity

### ISSUE THREAD

**Issue by Papagaai35** [ecmwf-projects/thermofeel#4]
The regular WBGT index consists of a weighted average of three thermometers. The natural wet bulb (an unventilated, exposed wet-bulb thermometer) accounts for 70% of this average, and is hugely dependent on the amount of moisture in the air. However, in your calculation of the WBGT, humidity is not a factor.

How do you calculate the WBGT in the function `calculate_wbgt` and what is your source for that calculation?
I have looked at [thermofeel/docs/guide/wbgt.rst](https://github.com/ecmwf-projects/thermofeel/blob/master/docs/guide/wbgt.rst), but your source still isn't clear to me...

**Comment by chlobrim** [comment]
Hello - we have a short communication submitted.
 We use the resolved quartic equation which calculates WBGT from Mean Radiant Temperature, which is referenced to in the docs. And is an alternative to using the 3 thermometers approach as suggested by de dear.
![image](https://user-images.githubusercontent.com/85228527/124599038-28a29300-de5d-11eb-8569-66eca41dfc5c.png)
This is the equation which does not use humidity. But does use emissivity and convection coefficient. 

This is in the paper by Guo et al 2018 which is in our docs and explains further. This is because of the relationship between air temperature and mean radiant temperature and natural wet bulb. Hope that helps.

**Comment by tlmquintino** [comment]
Many thanks for your feedback.
On further inspection, following your comments, my colleague @chlobrim corrected the code to include the temperature averaging including the natural wet bulb. This is now corrected in version >= **1.0.3**.

@Papagaai35 if you could possibly have a look and let us know if we can consider the issue closed or more analysis is required.

**Comment by tlmquintino** [comment]
As mentioned above, this issue is now resolved.
